rails_app/stop_bannon/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index', as: 'home'
  get 'home/about', as: 'about'
  get 'home/scripts', as: 'scripts'

end

rails_app/stop_bannon/app/models/politician.rb
class Politician < ActiveRecord::Base
end

rails_app/stop_bannon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  FULL_STATES = { "Alabama" => "AL" , "Alaska" => "AK", "Arizona" => "AZ", "Arkansas" => "AR",
  "California" => "CA" , "Colorado" => "CO",  "Connecticut" => "CT", "Delaware" => "DE",
  "District Of Columbia" => "DC", "Florida" => "FL", "Georgia" => "GA", "Hawaii" => "HI",
  "Idaho" => "ID", "Illinois" => "IL", "Indiana" => "IN", "Iowa" => "IA", "Kansas" => "KS",
  "Kentucky" => "KY", "Louisiana" => "LA", "Maine" => "ME", "Maryland" => "MD",
  "Massachusetts" => "MA", "Michigan" => "MI", "Minnesota" => "MN", "Mississippi" => "MS",
  "Missouri" => "MO", "Montana" => "MT", "Nebraska" => "NE", "Nevada" => "NV",
  "New Hampshire" => "NH", "New Jersey" => "NJ", "New Mexico" => "NM", "New York" => "NY",
  "North Carolina" => "NC", "North Dakota" => "ND", "Ohio" => "OH", "Oklahoma" => "OK",
  "Oregon" => "OR", "Pennsylvania" => "PA", "Puerto Rico" => "PR", "Rhode Island" => "RI",
  "South Carolina" => "SC", "South Dakota" => "SD", "Tennessee" => "TN", "Texas" => "TX",
  "Utah" => "UT",  "Vermont" => "VT", "Virginia" => "VA", "Washington" => "WA",
  "West Virginia" => "WV", "Wisconsin" => "WI", "Wyoming" => "WY" }.invert
end

rails_app/stop_bannon/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    @politicians = Politician.order(:last_name)

    @states = Hash.new
    @politicians.each do |p|
      if @states.key?(FULL_STATES[p.state])
        @states[FULL_STATES[p.state]].push(p)
      else
        @states[FULL_STATES[p.state]] = [p]
      end

      number = p.phone.gsub(/[^0-9]/, '')
      a, b, c = number[0..2], number[3..5], number[6..-1]
      p.phone = [a, b, c].join('-')
    end
    #TODO sort states
    #@states = @states.sort
  end
end

rails_app/stop_bannon/app/controllers/politicians_controller.rb
require 'csv'
class PoliticiansController < ApplicationController

  def index
    @politicians = Politician.all
  end

  def new
  end

  def create(params)
    @politician = Politician.new(params)
    @politician.save
  end

end

rails_app/stop_bannon/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app/stop_bannon/app/helpers/home_helper.rb
module HomeHelper
end

rails_app/stop_bannon/app/views/home/about.html.erb
<div class="col-sm-12">
<%= link_to 'HOME', home_path %>
<%= link_to 'SCRIPTS', scripts_path %>
<h1>About</h1>
<p>
President-elect Trump has appoint as chief strategist and senior counselor Steve Bannon, a leading figure of the alt-right and white supremacist movement and past executive chairman of the Breitbart News Network. He has repeatedly proven himself a racist, anti-Semitic, and misogynist, making him thoroughly unfit to serve one of the highest positions of our nation. We are determined to do all in our power to reverse this terrible choice, and we need your help.
</p>
<p>
Bannon's appointment is theoretically unchecked, but could be reversed if political leaders denounce this appointment and put pressure on President-elect Trump to do so. We must reach out to these political leaders and push them to denounce this appointment. In addition to securing the removal of Bannon, we also want to send a message to the Trump administration that we will not let its racism be normalized, and that we are prepared to oppose the choices of President-elect Trump.
</p>
<p>
Watch this page for resources and information about what we can do. <%= link_to 'HERE', scripts_path %> are scripts you can use to call yours senators and represantives.
</p>
<p>
The *most* effective way to call for action is by calling senators, congressmen, and representatives at their state offices. Visit <%= link_to 'HERE', home_path %> for their contact information.
</p>
<p>
  Visit <a href = 'https://www.splcenter.org/stephen-bannon-has-no-business-white-house'>petition</a> to sign the Southern Poverty Law Center's petition and pledge your support for this cause
</p>
</div>

rails_app/stop_bannon/app/views/home/index.html.erb
<div class="col-sm-12">
<%= link_to 'ABOUT', about_path %>
<%= link_to 'SCRIPTS', scripts_path %>

<h1>Stop Steve Bannon</h1>
<% @states.each do |state, pols| %>
  <h2><%= state %></h2>
  <table>
    <tr>
      <th class="col-md-1" align="left">Position</th>
      <th class="col-md-2" align="left">First Name</th>
      <th class="col-md-2" align="left">Last Name</th>
      <th class="col-md-2" align="left">Party</th>
      <th class="col-md-2" align="left">Denounced Bannon?</th>
      <th class="col-md-2" align="left">Phone</th>
    </tr>
  <% pols.each do |data| %>
    <tr>
      <td><%= data.position=='Sen' ? 'Sen' : 'Rep' %></td>
      <td><%= data.first_name %></td>
      <td><%= data.last_name %></td>
      <td><%= data.party=='D' ? 'Democrat' : 'Republican'%> </td>
      <td><%= data.denounced ? 'Denounced' : 'Call him/her!'%></td>
      <td><%= data.phone %></td>
    </tr>
  <% end %>
  </table>
<% end %>
<div class="col-sm-12">

<div class = 'contact'>
  Contact: salinawu at uchicago dot edu
</div>

rails_app/stop_bannon/app/views/home/scripts.html.erb
<div class="col-sm-12">
<%= link_to 'HOME', home_path %>
<%= link_to 'ABOUT', about_path %>
<h1>Scripts</h1>

<h5>Adapted from <a href = 'https://medium.com/@samala/for-the-love-of-all-that-is-holy-and-good-stopbannons-appointment-9880c4cb83b3#.n8isy7ikd' target="_blank">Samala</a> on Medium</h5>

<h3>For Democratic Senators and Representatives:</h3>
<ul>
<li>
  “Hello, my name is [your name]. I am a constituent, living in [address, district]. I am horrified at the news of Trump appointing Steve Bannon, a white supremacist, as one of his closest advisors. Please publicly condemn this appointment”
</li>
<li>
  “Hello, I am your constituent from [your location] and I was wondering when [legislator’s name] was planning on releasing a statement condemning Steve Bannon, the white supremacist who Donald Trump has appointed as his chief strategist.” (from @foundbysara)
</li>
<li>
  “Does [legislator’s name] agree with Harry Reid that Bannon’s appointment sends a dangerous signal that white supremacists “will be represented at the highest levels” in Trump’s administration? If so, please publicly condemn this appointment immediately.”
</li>
<li>
  “I am frightened by this as a [woman, as a Jewish person, as a Muslim person, as a black person, a queer person, etc.] American and I am asking [legislator’s name] to speak out against this appointment immediately, to make it clear that this is not acceptable. Can [legislator’s name] commit to standing with Harry Reid and speaking out publicly?”
</li>
<li>
  If the person responds that the representative has no intention of condemning Bannon, say, “I will call back tomorrow.” And call back tomorrow.
</li>
</ul>
<h3>For Republican Senators and Representatives:</h3>
<ul>
<li>
  “Hello, my name is [your name]. I am a constituent, living in [address, district]. I am horrified at the news of Trump appointing Steve Bannon, a white supremacist, as one of his closest advisors.”
</li>
<li>
  “How does [legislator’s name] feel about this appointment? Does this appointment represent his/her views? I am frightened by this [woman, as a Jewish person, as a Muslim person, as a black person, a queer person, etc.] and I am asking [legislator’s name] to speak out against this appointment immediately, to make it clear that this is not OK with mainstream Republicans.”
</li>
<li>
  “I believe that Bannon’s appointment sends a dangerous signal that white supremacists will be represented at the highest levels in Trump’s administration. Can [legislator’s name] commit to speaking out publicly against this appointment?”
</li>
<li>
  If the person responds that the representative has no intention of condemning Bannon, say, “I will call back tomorrow.” And call back tomorrow.
</li>
</ul>
<div class="col-sm-12">

rails_app/stop_bannon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StopBannon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>